# .goreleaser.yml
# Build customization
builds:
  - binary: om
    main: ./cmd/mobile/main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
archive:
  format: tar.gz
  